-
	id: gp-custom-css
	section: general
	label: 'Custom CSS'
	type: css 
	rows: 8
	std: ''
	
-
	id: gp-custom-js
	section: general
	label: 'Custom JS'
	type: javascript 
	rows: 8
	std: ''

-
	id: gp-analytics
	section: general
	label: 'Google Analytics'
	type: textarea-simple
	rows: 4
	std: ''

-
	id: gp-nav-layout
	section: header 
	label: 'Header layout'
	type: select
	std: 'top-bar'
	choices:
		- 
			value: 'simple'
			label: 'Simple (one row)'
		-
			value: 'top-bar'
			label: 'Top bar navigation'
	
-
	id: gp-home-slider
	section: header
	label: 'Homepage slider'
	desc: '<p>Shortcode for homepage slider (MetaSlider or RevSlider). Leave blank for disable.</p>'
	type: 'text'
	std: ''
	
-
	id: header-logo-textlock
	section: header
	label: ""
	desc: "<h1>Logo settings</h1><hr />"
	type: textblock

-
	id: gp-logo
	section: header
	label: 'Your site logo'
	description: 'Upload a logo (png) or leave blank for text-based logo'
	type: upload
	std: ''
	
-
	id: gp-hidden-nav-logo
	section: header
	label: 'Hide logo in the navbar'
	desc: '<p>Enable this if you want to hide logo in the main navigation bar</p>'
	type: 'on-off'
	std: 'off'
	
-
	id: header-navigations-textbox
	section: header
	label: ""
	desc: "<h1>Navigation settings</h1><hr />"
	type: textblock

-
	id: gp-primary-nav-float
	section: header
	label: "Primary navigation floating"
	desc: ""
	type: select
	choices:
		-
			value: left
			label: Left
		-
			value: right
			label: Right
	std: 'left'
	
-
	id: gp-secondary-nav-float
	section: header
	condition: 'gp-nav-layout:not(simple)'
	label: "Secondary navigation floating"
	desc: ""
	type: select
	choices:
		-
			value: left
			label: Left
		-
			value: right
			label: Right
	std: 'left'

-
	id: gp-nav-hover-dropdowns
	section: header
	label: 'Hover dropdowns'
	desc: '<p>By default, dropdown menus triggered with click. If you enable this options dropdown menus will be triggered at hover.</p>'
	type: 'on-off'
	std: 'off'
	
-
	id: gp-nav-disable-mobile-dropdowns
	section: header
	label: 'Force one-level navigation on mobile'
	desc: '<p>If Hover dropdowns is enabled, you can disable the second level navigation on mobile devices. If you don\'t disable it, the parent menuitem can\'t be a link.</p>'
	type: 'on-off'
	std: 'off'
	condition: 'gp-nav-hover-dropdowns:is(on)' #this option only needed if hover dropdowns are enabled

-
	id: header-social-textblock
	section: header
	ifcfg: gp_allow_nav_social
	label: ""
	desc: "<h1>Header social links</h1><hr />"
	type: textblock

-
	id: gp-nav-social-enabled
	section: header
	ifcfg: gp_allow_nav_social
	label: 'Show social links in header'
	desc: '<p>Enable or disable header social icons like Facebook, Twitter, etc...</p>'
	type: 'on-off'
	std: 'off'
	
-
	id: gp-nav-social-position
	section: header
	ifcfg: gp_allow_nav_social
	condition: 'gp-nav-layout:not(simple),gp-nav-social-enabled:is(on)'
	label: 'Social links position'
	desc: '<p></p>'
	type: 'select'
	choices:
		-
			value: top
			label: Top
		-
			value: bottom
			label: Bottom
	std: 'bottom'
	
-
	id: gp-nav-social-float
	section: header
	ifcfg: gp_allow_nav_social
	condition: 'gp-nav-social-enabled:is(on)'
	label: 'Social links floating'
	desc: '<p></p>'
	type: 'select'
	choices:
		-
			value: left
			label: Left
		-
			value: right
			label: Right
	std: 'right'

-
	id: header-search-textblock
	section: header
	ifcfg: gp_allow_nav_search
	label: ""
	desc: "<h1>Header search</h1><hr />"
	type: textblock
	
-
	id: gp-nav-search
	section: header
	ifcfg: gp_allow_nav_search
	label: 'Show search form in header'
	desc: '<p>Enable or disable header search form</p>'
	type: 'on-off'
	std: 'off'

-
	id: gp-nav-search-float
	section: header
	ifcfg: gp_allow_nav_search
	condition: 'gp-nav-search:is(on)'
	label: 'Search form floating'
	desc: ''
	type: 'select'
	choices:
		-
			value: left
			label: Left
		-
			value: right
			label: Right
	std: 'right'

-
	id: header-language-switcher-textbox
	section: header
	ifcfg: gp_allow_nav_language_switcher
	label: ""
	desc: "<h1>Header language switcher</h1><p class='desc'>Polylang must be installed for this feature. See Install Plugins section.</p><hr />"
	type: textblock

-
	id: gp-nav-language-switcher
	section: header
	ifcfg: gp_allow_nav_language_switcher
	label: 'Show language switcher in header'
	desc: '<p>Enable or disable header language switcher</p>'
	type: 'on-off'
	std: 'off'
	
-
	id: gp-nav-language-switcher-position
	section: header
	ifcfg: gp_allow_nav_language_switcher
	condition: 'gp-nav-layout:not(simple),gp-nav-language-switcher:is(on)'
	label: 'Language switcher position'
	desc: '<p></p>'
	type: 'select'
	choices:
		-
			value: top
			label: Top
		-
			value: bottom
			label: Bottom
	std: 'bottom'
	
-
	id: gp-nav-language-switcher-float
	section: header
	ifcfg: gp_allow_nav_language_switcher
	condition: 'gp-nav-language-switcher:is(on)'
	label: 'Language switcher floating'
	desc: ''
	type: 'select'
	choices:
		-
			value: left
			label: Left
		-
			value: right
			label: Right
	std: 'right'
	
-
	id: gp-social-links
	section: social
	ifcfg: gp_allow_nav_social
	label: 'Social links'
	type: list-item
	settings:
		-
			id: gp-nav-social-href
			label: 'Link'
			type: text
		-
			id: gp-nav-social-site 
			type: select 
			label: 'Type'
			choices:
				-
					value: ''
					label: '-- select --'
				-
					value: 'facebook'
					label: 'Facebook'
				-
					value: 'twitter'
					label: 'Twitter'
				- 
					value: 'google'
					label: 'Google +'
				- 
					value: 'pinterest'
					label: 'Pinterest'
				-
					value: 'linkedin'
					label: 'LinkedIN'
				-
					value: 'github'
					label: 'GitHub'
				-
					value: 'foursquare'
					label: 'FourSquare'
				-
					value: 'feedburner'
					label: 'FeedBurner'
				-
					value: 'soundcloud'
					label: 'SoundCloud'
				-
					value: 'youtube'
					label: 'YouTube'
				-
					value: 'vimeo'
					label: 'Vimeo'
				-
					value: 'instagram'
					label: 'Instagram'
				-
					value: 'wordpress'
					label: 'WordPress'
					
-
	id: gp-footer-text
	section: footer
	label: 'Footer text'
	desc: '<p>Set up your footer text like copyright stuff, some links, etc... HTML allowed!</p>'
	type: 'textarea'
	std: ''

-
	id: gp-slider-plugin
	section: install-plugins
	label: 'Install a slider plugin'
	desc: '<p>GeckoPress supports multiple slider plugins in order to allow you to select the best fitting one for your site.</p><p>MetaSlider is a lightweight slider plugin working with four slider scripts. Easy to use and optimized for speed and seo.<br />Revolution Slider is a heavy-weight, full-feutured slider scripts. It allows you to do anything with your slides, like frames, animations and a lot of cool stuff.</p><p><a class="button button-primary thickbox" href="/wp-admin/plugin-install.php?tab=plugin-information&plugin=ml-slider&TB_iframe=true&width=600&height=550">Install MetaSlider</a> <a class="button button-secondary" target="_blank" href="http://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380">Buy RevSlider</a></p>'
	type: 'textblock-titled'
	
-
	id: gp-contact-form-plugin
	section: install-plugins
	label: 'Install Contact Form 7'
	desc: '<p>Contact Form 7 is needed to display your contact forms. You can use any other contact form plugin, but GeckoPress has front-end codes only for CF7.</p><p><a class="button button-primary thickbox" href="/wp-admin/plugin-install.php?tab=plugin-information&plugin=contact-form-7&TB_iframe=true&width=772&height=865">Install Contact Form 7</a></p>'
	type: 'textblock-titled'
	
-
	id: gp-page-builder-plugin
	section: install-plugins
	label: 'Install PageBuilder by Siteorign'
	desc: '<p>Page Builder by SiteOrigin makes it easy to build responsive grid-based page content that adapts to mobile devices with pixel perfect accuracy. It\'s a whole new dimension to content creation that\'ll help you create your home, contact, about us or any other page where a linear layout won’t convey your message. It\'s a powerful enhancement to the WordPress content editing experience, yet it feels entirely familiar.</p><p><a class="button button-primary thickbox" href="/wp-admin/plugin-install.php?tab=plugin-information&plugin=siteorigin-panels&TB_iframe=true&width=600&height=550">Install PageBuilder by Siteorigin</a></p>'
	type: 'textblock-titled'
	
-
	id: gp-seo-plugin
	section: install-plugins
	label: 'Install Yoast SEO'
	desc: '<p>This plugin is written from the ground up by Joost de Valk and his team at Yoast to improve your site\'s SEO on all needed aspects. While this Yoast SEO plugin goes the extra mile to take care of all the technical optimization, more on that below, it first and foremost helps you write better content. Yoast SEO forces you to choose a focus keyword when you\'re writing your articles, and then makes sure you use that focus keyword everywhere.</p><p><a class="button button-primary thickbox" href="/wp-admin/plugin-install.php?tab=plugin-information&plugin=wordpress-seo&TB_iframe=true&width=772&height=865">Install Yoast SEO</a></p>'
	type: 'textblock-titled'
	
-
	id: gp-cache-plugin
	section: install-plugins
	label: 'Install W3 Total Cache'
	desc: '<p>W3 Total Cache improves the user experience of your site by increasing server performance, reducing the download times and providing transparent content delivery network (CDN) integration.</p><p><a class="button button-primary thickbox" href="/wp-admin/plugin-install.php?tab=plugin-information&plugin=w3-total-cache&TB_iframe=true&width=600&height=550">Install W3 Total Cache</a></p>'
	type: 'textblock-titled'
	
-
	id: gp-security-plugin
	section: install-plugins
	label: 'Install WordFence'
	desc: '<p>The most downloaded WordPress security plugin. Wordfence starts by checking if your site is already infected. We do a deep server-side scan of your source code comparing it to the Official WordPress repository for core, themes and plugins. Then Wordfence secures your site and makes it up to 50 times faster.</p><p><a class="button button-primary thickbox" href="/wp-admin/plugin-install.php?tab=plugin-information&plugin=wordfence&TB_iframe=true&width=772&height=865">Install WordFence</a></p>'
	type: 'textblock-titled'