customcss:
	id: gp-custom-css
	section: general
	label: 'Egyedi CSS'
	desc: '<p>Egyedi CSS kód, amely a &lt;head&gt; szekcióba kerül minden lapletöltéskor.</p>'
	type: css 
	rows: 8

analytics:
	id: gp-analytics
	section: general
	label: 'Google Analytics'
	desc: 'Google Analytics követőkód.'
	type: textarea-simple
	rows: 4
			
nav-social:
	id: gp-nav-social
	section: header
	label: 'Show social stuff in header'
	desc: '<p>Enable or disable header social icons like Facebook, Twitter, etc...</p>'
	type: 'on-off'
	
nav-search:
	id: gp-nav-search
	section: header
	label: 'Show search form in header'
	desc: '<p>Enable or disable header search form</p>'
	type: 'on-off'
		